### ISSUE TITLE
How to read data from numPy file.

### ISSUE THREAD

**Issue by dpnkrg** [Kotlin/multik#1]
Hi All,

How to read (data from) numPy file?

My numPy file is stored in the internal storage of the Android App. I want to read/access the data inside in numPy file through the Android App.

Any help or sugreesion?

**Comment by breandan** [comment]
You might be able to use this library: https://github.com/JetBrains-Research/npy

**Comment by devcrocod** [comment]
Has breandan suggestion helped you?
