### ISSUE TITLE
multik java.lang.unsatisfiedlinkerror: dlopen failed: library "libmultik_jni.so" not found

### ISSUE THREAD

**Issue by Sungijnwoo** [Kotlin/multik#103]
i use multik to calculate eigen value and vector in android 
but it doesn't work 

how can i deal with this

my dependencies is
    implementation("org.jetbrains.kotlinx:multik-api:0.1.1")
    implementation("org.jetbrains.kotlinx:multik-jvm:0.1.1")

and i also tried "default" but it also doesn't work

this problem caused by "mk.linalg.eig(_)"

**Comment by devcrocod** [comment]
Hi,

What other dependencies are you using?

**Comment by CeyssensHelder** [comment]
Hello there,

I seem to have the same issue.

I get this when trying to use DefaultLinAlg.norm()

I use the following dependencies:
```
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'

    def camerax_version = "1.0.0-alpha05"
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"

    implementation 'org.pytorch:pytorch_android_lite:1.10.0'
    implementation 'org.pytorch:pytorch_android_torchvision_lite:1.10.0'

    implementation 'com.google.guava:guava:31.1-jre'
    implementation 'commons-io:commons-io:2.11.0'

    implementation 'org.apache.commons:commons-math3:3.6.1'
    implementation "androidx.core:core-ktx:+"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation "org.jetbrains.kotlinx:multik-api:0.1.1"
    implementation "org.jetbrains.kotlinx:multik-default:0.1.1"

```

**Comment by devcrocod** [comment]
You are right, there is no native library for Android yet, so only multik-jvm works now.

Support for the native part is planned to release 0.2.0 (#104 )
