### ISSUE TITLE
Missing libmultik_jni.so when invoking math module in Android app.

### ISSUE THREAD

**Issue by occultus73** [Kotlin/multik#11]
Hi there. Excited about this new library. I'm currently using it to build a context bandit AI for an Android library.

Got a missing run time library here, when trying to execute this line that invokes the math module:
`return mk.math.argMax(vals)` 

Stack trace:
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.foo.sdk.ml.test-YJeG7qRKnhW-wJG8Fop5OQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.foo.sdk.ml.test-YJeG7qRKnhW-wJG8Fop5OQ==/lib/x86, /data/app/com.foo.sdk.ml.test-YJeG7qRKnhW-wJG8Fop5OQ==/base.apk!/lib/x86, /system/lib]]] couldn't find "libmultik_jni.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
	at java.lang.System.loadLibrary(System.java:1669)
	at org.jetbrains.kotlinx.multik.jni.Loader.load(Loader.kt:56)
	at org.jetbrains.kotlinx.multik.jni.NativeEngine.<clinit>(NativeEngine.kt:26)
	at org.jetbrains.kotlinx.multik.default.DefaultEngine.<clinit>(DefaultEngine.kt:24)
	at org.jetbrains.kotlinx.multik.default.DefaultEngineProvider.getEngine(DefaultEngine.kt:12)
	at org.jetbrains.kotlinx.multik.api.Engine.loadEngine(Engine.kt:36)
	at org.jetbrains.kotlinx.multik.api.Engine.<clinit>(Engine.kt:67)
	at org.jetbrains.kotlinx.multik.api.Multik.getMath(Multik.kt:39)
```

I'm importing the library as per the GitHub README:

```
repositories {
    mavenCentral()
    //etc...
}

dependencies {
    //etc...

    // NDArray Library
    implementation("org.jetbrains.kotlinx:multik-api:0.0.1")
    implementation("org.jetbrains.kotlinx:multik-default:0.0.1")
}
```

Thank you for your attention.

**Comment by occultus73** [comment]
Update: seem to have fixed it by switching from `multik-default` to `multik-jvm` - which is odd because I thought the former includes the latter? Perhaps I was supposed to run those gradle commands mentioned in the README under _Building_ manually.

You'll forgive me if I'm a little slow and clumsy with sort of thing.

**Comment by devcrocod** [comment]
`multik-default` includes two implementations jvm and native. They complement each other. So in the `multik-default` `dot` method from native, as it is faster than in jvm. And sliced methods such as `sum2D` from jvm. There are no such methods in the native.

We are going to support the native module and, accordingly, the default for android.

**Comment by occultus73** [comment]
As it happens, I was previously using the Nd4j library on this project, and the native runtime libraries that came with that were absurdly huge. With `multik-jvm, there are no such 'humongous_jni.so' binaries to speak of, and R8 can rip out everything I don't need. Size is more of priority for me than speed.

**Comment by mingen-pan** [comment]
Hi, I have a similar problem when using `multik-default`.

May I ask if there is timeline on when `multik-default` will be supported for Android?

**Comment by devcrocod** [comment]
Unfortunately, due to logistical problems with build agents, I cannot say when the android artifact will be ready.
