### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by cagriyildirimR** [Kotlin/multik#117]
I got this error on Fedora35

> Task :multik-openblas:build_cmake FAILED
[ 53%] Built target openblas
Consolidate compiler generated dependencies of target multik_jni-linuxX64
gmake[3]: *** No rule to make target '/libquadmath.a', needed by 'libmultik_jni-linuxX64.so'.  Stop.
gmake[2]: *** [CMakeFiles/Makefile2:111: CMakeFiles/multik_jni-linuxX64.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/multik_jni-linuxX64.dir/rule] Error 2
gmake: *** [Makefile:137: multik_jni-linuxX64] Error 2

cmake version 3.22.2
gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)
GNU Fortran (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)

**Comment by devcrocod** [comment]
To build a native library, you need to link with libquadmath.
set the `GCC_LIB_Path` environment variable with the path to the gcc (`export GCC_LIB_Path=[path to libs of gcc]) libraries or pass it in the [script](https://github.com/Kotlin/multik/blob/b328935490f920161950f668cfc175179a9b1bf8/gradle/multik_jni-cmake.gradle#L31).

**Comment by cagriyildirimR** [comment]
Thanks. That solved the problem.
