### ISSUE TITLE
How to manually clear a mk.ndarray

### ISSUE THREAD

**Issue by RachelLYY** [Kotlin/multik#136]
I'm using mk.ndarray to represent a model's output, but the output is very large, about 25000. Based on this output, I first filter the elements that are useful for me. After this step, I want to clear this large output mk.ndarray. I searched the API and don't find any remove or clear operation. What should I do? Thanks.

**Comment by koodzi** [comment]
If by clear you mean making all the elements zeros then you can just multiply by zero.
```kotlin
val x = mk.d3array(2, 2, 3) { it * it };
x * 0
```

**Comment by devcrocod** [comment]
Do you mean set all elements to 0 in the array?

**Comment by RachelLYY** [comment]
> 

I want to set this ndarray as empty to not occupy memory anymore.

**Comment by devcrocod** [comment]
You can set a ndarray as null, and gc will remove the ndarray when it runs
