### ISSUE TITLE
Gradle dependency error for multiplatform commonMain implementation.

### ISSUE THREAD

**Issue by occultus73** [Kotlin/multik#17]
Trying to import the Multik library into a multiplatform module, I'm finding Gradle is getting in a muddle with its maven repositories.

```
kotlin {
    ...
    sourceSets {
        val commonMain by getting {
            repositories {
                mavenCentral()
            }

            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3-native-mt")
                implementation("org.jetbrains.kotlinx:multik-api:0.0.1")
                implementation("org.jetbrains.kotlinx:multik-default:0.0.1")
            }
        }
        ...
```

Gradle sync yields this error:
```
<ij_msg_gr>Gradle import errors<ij_msg_gr>
<ij_nav>/home/john/StudioProjects/foo-android-ml-sdk/bandit/build.gradle.kts<ij_nav>
<i>
   <b>project ':bandit': Unable to build Kotlin project configuration</b>
   Details: org.gradle.internal.resolve.ArtifactNotFoundException: 
   Could not find multik-api-0.0.1-samplessources.jar (org.jetbrains.kotlinx:multik-api:0.0.1).
   Searched in the following locations:
   https://jcenter.bintray.com/org/jetbrains/kotlinx/multik-api/0.0.1/multik-api-0.0.1-samplessources.jar
</i>
```
It's looking for multik-api-0.0.1-samplessources.jar on jcenter, not mavenCentral.

Here's a similar incident of something like this happening here:
https://stackoverflow.com/questions/57396309/gradle-try-to-download-from-wrong-repository

Could there be a misconfigured entry for _multik-api-0.0.1-samplessources_ in a _pom.xml_ file somewhere?

**Comment by devcrocod** [comment]
You can only use multiplatform libraries in multiplatform projects. At the moment multik is only for jvm.
Multik can be published as multiplatform when we can remove jvm dependencies like `ServiseLoader`.

**Comment by occultus73** [comment]
> You can only use multiplatform libraries in multiplatform projects. At the moment multik is only for jvm.
> Multik can be published as multiplatform when we can remove jvm dependencies like `ServiseLoader`.

I don't suppose you could suggest a short term strategy for replacing ServiceLoader could you? I have been working with the source code directly. I commented out everywhere that used javaClass because it seemed non-essential. I also refactored all the Java collections to Kotlin collections the best I could. There were a couple of lines using "clone()" on number arrays, where "copyOf()" seemed more appropriate.

If I could just crack this ServiceLoader problem, I will be able to use the library in the commonModule.

**Comment by devcrocod** [comment]
Yes, we haven't looked at how to replace the ServiceLoader yet. We thought about a multiplatform, but this topic requires more detailed research in order to preserve the capabilities that we have now.

If you get the engine directly, then you won't be able to use the others.

**Comment by occultus73** [comment]
Well I very much hope you will convert Multik to a Multiplatform library as soon as you can so I can add it as a Gradle dependency!

**Comment by luca992** [comment]
@occultus73 https://github.com/Kotlin/multik/pull/20 just made an initial draft pr for multiplatform if you want to test out that branch
