### ISSUE TITLE
multik with spring boot 3.3, unable to access the classes from the module org.jetbrains.kotlinx.multik

### ISSUE THREAD

**Issue by fabriciokjc** [Kotlin/multik#206]
I am unable to access the classes from the module org.jetbrains.kotlinx.multik in my project. I believe there is an issue with the library. I am using version 0.2.3 of multik-kotlin, multik-core, and multik-default. I can only import the classes (NDArray, D2) from the module org.jetbrains.kotlinx.multik if I use the dependency multik-api version 0.1.1.
![image](https://github.com/user-attachments/assets/8842e6af-395f-4ccf-8689-759bcf4f766a)

When using the multik-api library, I am getting the following error when trying to perform the operation: 
Multik.linalg.dot(embeddingsMatrix, queryArray)
![image](https://github.com/user-attachments/assets/16790d25-014d-4314-bb04-8a780cbb4f5c)

I tried using Multik.setEngine(DefaultEngineType), but there is no implementation of EngineType in the multik-api library.

This is a snippet of the code that gives an error when using multik-api version 0.1.1
![image](https://github.com/user-attachments/assets/5ccd68ea-3e4b-4b7e-97f7-32fc97c11507)

**Comment by devcrocod** [comment]
I see that the problem lies in the metadata of the multiplatform library. You should use a direct dependency. In your case, it is `org.jetbrains.kotlinx:multik-core-jvm:0.2.3`.

**Comment by devcrocod** [comment]
And you are using `multik-default` and `multik-kotlin`. It's better to use just one of them. `multik-kotlin` - a pure Kotlin implementation. `multik-default` - a dependency that aggregates `multik-kotlin` and `multik-openblas`.

**Comment by fabriciokjc** [comment]
Using the 'multik-core-jvm' library solved the import issue, so I no longer need to use the 'multik-api' dependency. However, I still have a similar error as before.
![image](https://github.com/user-attachments/assets/613e3348-d457-4dcc-8063-4c3df21f7cc5)

**Comment by devcrocod** [comment]
Oh, sorry
For implementation dependency, you need to do the same thing.
so your maven should look like this:
```
<dependency>
    <groupId>org.jetbrains.kotlinx</groupId>
    <artifactId>dataframe</artifactId>
    <version>0.13.1</version>
</dependency>
<dependency>
    <groupId>org.jetbrains.kotlinx</groupId>
    <artifactId>multik-core-jvm</artifactId>
    <version>0.2.3</version>
</dependency>
<dependency>
    <groupId>org.jetbrains.kotlinx</groupId>
    <artifactId>multik-kotlin-jvm</artifactId>
    <version>0.2.3</version>
</dependency>
```

**Comment by fabriciokjc** [comment]
Man, doing it this way worked. Thank you very much for the help.

**Comment by fabriciokjc** [comment]
Man, doing it this way worked. Thank you very much for the help.
