### ISSUE TITLE
Broadcasting support?

### ISSUE THREAD

**Issue by luca992** [Kotlin/multik#21]
Any plans to add support for [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)? 

In the meantime what is the most efficient way to repeat or tile an NDArray in multik.

I've tried something like:
```
    // rowND is a NDArray
    val row = rowND.toList()
    val numRows = 1000
    val repeatedRows = mk.ndarray(Array(numRows) { row }.asList())
```

not sure if there's a faster way

**Comment by devcrocod** [comment]
No, we have no plans to support broadcasting.

**Comment by hakanai** [comment]
This is probably faster:

```kotlin
    val a = mk.ndarray(
        mk[
            mk[1, 2, 3, 4],
            mk[5, 6, 7, 8],
            mk[9, 10, 11, 12],
        ]
    )
    println("a = \n$a")

    val b = mk.ndarray(
        mk[2, 3, 2, 3]
    )
    val row = b.toIntArray()
    println("b = \n$b")

    val bBroadcasted = mk.ndarray(Array(a.shape[0]) { row })

    println("a * b = \n${a * bBroadcasted}")
```

`toList()` seems to use iteration to produce the list, whereas the array can be a direct copy if the source is consistent.
