### ISSUE TITLE
How to add an element to the end of a `D1Array`

### ISSUE THREAD

**Issue by johanvergeer** [Kotlin/multik#22]
A new array instance is created with the element added when using the `+` operator on a regular Kotlin Array.

```kotlin
val f = DoubleArray(5) { 100.0 }
// [100.0, 100.0, 100.0, 100.0, 100.0]
val b = 150.0

val c = f + b
// [100.0, 100.0, 100.0, 100.0, 100.0, 150.0]
```

But the given values is added to each value in the array when the same `+` operator is used on an `ndarray`, which makes sense from a math perspective.

```kotlin
val f = mk.ndarray(DoubleArray(5) { 100.0 })
// [100.0, 100.0, 100.0, 100.0, 100.0]
val b = 150.0

val c = f + b
// [250.0, 250.0, 250.0, 250.0, 250.0]
```

But how can I just add an item to the array like I did in the first example. 

For now I've used a pretty naive approach, but I think there should be a better way.

```kotlin
val retval = mk.empty<Double, D1>(6)
for (i in f.indices) {
    retval[i] = f[i]
}
retval[5] = b

println(retval)
// [100.0, 100.0, 100.0, 100.0, 100.0, 150,0]
```

**Comment by devcrocod** [comment]
In math libraries, the `+` operator with scalars is used as element-wise addition.

Adding an element or other array to the end is currently not available out of the box.

We will definitely add it.

If you often use such an operation, then your method can be moved into a separate function. You can also do this:
```kotlin
val f = mk.ndarray(DoubleArray(5) { 100.0 })
val c = mk.ndarray(a.toList() + 150.0)
```
But this option will use an additional sheet and is not recommended for large arrays.

**Comment by devcrocod** [comment]
#24
