### ISSUE TITLE
Kotlin multiplatform

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/multik#23]

**Comment by occultus73** [comment]
Nice. Don't forget, a tweek here and there could get this working for Kotlin JS too. I managed it.

**Comment by devcrocod** [comment]
- [x] multik-api
    - [x] jvm
    - [x] js
    - [x] native
- [x] multik-jvm
    - [x] jvm
    - [x] js
    - [x] native
- [x] multik-native
    - [x] jvm
    - [x] native
- [ ] multik-default
    - [x] jvm
    - [ ] js
    - [ ] native
 
The basis of the multiplatform is already there. At the moment, the issue of native support for Android and macOS aarch64 is being resolved.
