### ISSUE TITLE
mk.math.maxD4() doesn't work

### ISSUE THREAD

**Issue by H43RO** [Kotlin/multik#27]
`val tensor = mk.ndarray(output, 272, 480, 7, 4)`
 `val result = mk.math.maxD4(tensor, axis = 1)`

If I execute the above action, Logcat as below will appear and the app will be forced to shut down. I don't know the cause.

<img width="1704" alt="스크린샷 2021-05-16 오후 11 36 23" src="https://user-images.githubusercontent.com/30336663/118401169-8a395300-b69f-11eb-8cdb-c0bf74294114.png">

**Comment by H43RO** [comment]
I've done all of these things, including allowing `Deprecated NDK` and  setting `Hardware Acceleration` to false.

**Comment by devcrocod** [comment]
Are you using the default module?

The default module uses jvm and native implementations. The native implementation does not currently support Android. Although the `max4D()` function is implemented in jvm, the library still tries to load the native library `ibmultik_jni.so`, as a result of which this error appears.

For now, please use `multik-jvm` for android.
