### ISSUE TITLE
How to create MutableMultiArray with custom data type?

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/multik#33]
I am trying to create a matrix of `Apcomplex` (wrapper class around BigDecimal). When I call `mk.empty<Apcomplex, D2>` I get `java.lang.IllegalStateException: One of the primitive types was expected, got org.apfloat.Apcomplex`.

**Comment by devcrocod** [comment]
Only primitive types are supported: `Byte`, `Short`, `Int`, `Long`, `Float`, `Double`. Since the implementation is based on primitive arrays.

BigDecimal support is planned.
