### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by Lundez** [Kotlin/multik#39]
Hi,

Wondering how much effort is put into this? The performance is not really on par with `kmath` or `viktor` and I'm not seeing a lot of effort put into the library going by commits.

Is this project in maintenance mode already?

- Hampus

**Comment by devcrocod** [comment]
Hi!

Now all the activity takes place in the v0.0.2 and multik-cuda branches.

We're concerned about performance, if you have any feedback I'd love to hear from you. One of the maintainer viktor [compared the performance of different libraries](https://github.com/dievsky/kotlin-math-benchmark) and multik showed good results.

At the moment I'm busy with another library, so the release of version 0.0.2 is delayed

**Comment by Lundez** [comment]
Ah, awesome to hear that those branches are active!

That was actually the exact benchmark I was looking at. I would expect multik to be on par with a naïve loop or `kmath` in most if not all scenarios. Looking at the `dot` benchmark we see the following:
![image](https://user-images.githubusercontent.com/7490199/128374728-ad1aa436-7180-4d0c-bbf2-8b0c65cc03f6.png)
Which means we start at ~10% of naïve java loop and end up below 50% of the speed. That's pretty slow (>2x slower). On GraalVM it is not really as close, but it's still performing worse.

**Comment by devcrocod** [comment]
You can take the new build `0.1.0-dev-1`
Many performance problems have been fixed there.
There will be a release soon.
