### ISSUE TITLE
Add LogicalOr and LogicalAnd

### ISSUE THREAD

**Issue by zaleslaw** [Kotlin/multik#48]
Hi, I'm going to implement the postprocessing for the YOLOv4 model in the KotlinDL library, but it requires many different analogs of the NumPy functions.

Could you please add the analog of the [`np.logical_or`](https://numpy.org/doc/stable/reference/generated/numpy.logical_or.html?numpy.logical_or) and  [`np.logical_and`](https://numpy.org/doc/stable/reference/generated/numpy.logical_and.html#numpy.logical_and)  functions?

**Comment by devcrocod** [comment]
In the yolo model, this is used to get masks by which arrays are subsequently taken.
```python
mask = np.logical_and(scale_mask, score_mask)
coors, scores, classes = pred_coor[mask], scores[mask], classes[mask]
```
There is no such thing in multik either. I need to think about the api.

**Comment by breandan** [comment]
Related to #37, it would be nice to have a Kotlin API for something like this: https://github.com/JetBrains-Research/spbla

**Comment by breandan** [comment]
@devcrocod I have been doing some experiments with abstract algebras using [type classes](https://kotlin.christmas/2020/7). Although I am still unhappy with the amount of indirection, our implementation currently supports various semirings. Perhaps you can borrow some ideas:

https://github.com/breandan/kaliningraph/blob/master/src/main/kotlin/ai/hypergraph/kaliningraph/matrix/MatrixAlgebra.kt

**Comment by devcrocod** [comment]
It looks very cool.
thanks
