### ISSUE TITLE
add native implementation of statistical functions

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/multik#62]

**Comment by cagriyildirimR** [comment]
Can you give a bit more detail about these functions? 

Are [numpy](https://numpy.org/doc/stable/reference/routines.statistics.html) statistical functions a good base case for this issue?

There is also an unsupported kotlin [statistics](https://github.com/thomasnield/kotlin-statistics) library.

In any case, I am willing to work on this issue.

**Comment by devcrocod** [comment]
Sorry, I missed your message.

Here we mean to add the implementation of already existing functions from multik-jvm.

In the general case, it is planned to expand the statistics interface. I think I will look at functions from numpy and partly from scipy.
