### ISSUE TITLE
Multik-native fails to inverse large matrix, but JVM succeeds

### ISSUE THREAD

**Issue by ccjernigan** [Kotlin/multik#74]
OVERVIEW
I'm seeing a failure to perform an inverse on a specific matrix with the native implementation of Multi, although it succeeds with the JVM implementation

STEPS TO REPRODUCE
1. Perform an inverse `mk.linalg.inv` on the attached matrix with multik-default or multik-native 0.1.0

RESULTS
Expected
Inverse succeeds, because it does correctly succeed on JVM.

Actual
Failure with the following.

I realize this is a large input, but I would at least expect relatively consistent behavior between the native and JVM implementations.

```
---------------  T H R E A D  ---------------

Current thread (0x00007f84772c5000):  JavaThread "pool-2-thread-1 @coroutine#10" [_thread_in_native, id=80131, stack(0x000070000f59a000,0x000070000f69a000)]

Stack: [0x000070000f59a000,0x000070000f69a000],  sp=0x000070000f58fb00,  free space=18014398509481942k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libmultik_jni.dylib+0xe42c0]  dgetrf_parallel+0x680

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.jetbrains.kotlinx.multik.jni.linalg.JniLinAlg.inv(I[DI)I+0
j  org.jetbrains.kotlinx.multik.jni.linalg.NativeLinAlgEx.invCommon(Lorg/jetbrains/kotlinx/multik/ndarray/data/MultiArray;)Lorg/jetbrains/kotlinx/multik/ndarray/data/NDArray;+126
j  org.jetbrains.kotlinx.multik.jni.linalg.NativeLinAlgEx.inv(Lorg/jetbrains/kotlinx/multik/ndarray/data/MultiArray;)Lorg/jetbrains/kotlinx/multik/ndarray/data/NDArray;+224
j  org.jetbrains.kotlinx.multik.default.linalg.DefaultLinAlgEx.inv(Lorg/jetbrains/kotlinx/multik/ndarray/data/MultiArray;)Lorg/jetbrains/kotlinx/multik/ndarray/data/NDArray;+10
j  org.jetbrains.kotlinx.multik.api.linalg.InverseKt.invD(Lorg/jetbrains/kotlinx/multik/api/linalg/LinAlg;Lorg/jetbrains/kotlinx/multik/ndarray/data/MultiArray;)Lorg/jetbrains/kotlinx/multik/ndarray/data/NDArray;+19

```

[matrix.txt](https://github.com/Kotlin/multik/files/7488617/matrix.txt)

**Comment by devcrocod** [comment]
Unfortunately, we cannot guarantee consistency between native and jvm implementations due to the fact that even the underlying algorithms are different.

OpenBlas has similar issues. In this case, the error occurs in the LU decomposition - dgetrf. I have it reproduced even in one thread, which is rather strange.

To fix this now for multi-threaded code, you need export OPENBLAS_NUM_THREADS=1 in the environment variables.
