### ISSUE TITLE
add `clamp`

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/multik#79]

**Comment by devcrocod** [comment]
@zaleslaw 
This is `clip` function.
The function looks like: `min(max(x, min_value), max_value)`
I have doubts about adding such a specific feature to Multik.

**Comment by devcrocod** [comment]
The function should be added as a MultiArray extension returning NDArray:
```kotlin
MultiArray<T, D>.clip(min: T, max: T): NDArray<T, D>
```
To add a function, you can use `map`, passing the logic written above

**Comment by cagriyildirimR** [comment]
I can do this one.

**Comment by devcrocod** [comment]
@cagriyildirimR, that's great!
Please note that all development is now in the v0.2.0 branch. Multiplatform has already been added there, since this function doesn't require any platform dependencies, all code can be put in common.
