### ISSUE TITLE
add converter NDArray to primitive arrays

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/multik#81]
There is a converter to a flat array, you need to add a converter to nested arrays:
```kotlin
MultiArray<Float, D?>.toFloatArrayD?(): Array<...<FloatArray>>
```
Similar to [`toListD2`](https://github.com/Kotlin/multik/blob/ad39af88a8521f24156d8f0fa101c343a651af59/multik-api/src/main/kotlin/org/jetbrains/kotlinx/multik/ndarray/operations/IteratingNDArray.kt#L1308), [`toListD3`](https://github.com/Kotlin/multik/blob/ad39af88a8521f24156d8f0fa101c343a651af59/multik-api/src/main/kotlin/org/jetbrains/kotlinx/multik/ndarray/operations/IteratingNDArray.kt#L1318), [`toListD4`](https://github.com/Kotlin/multik/blob/ad39af88a8521f24156d8f0fa101c343a651af59/multik-api/src/main/kotlin/org/jetbrains/kotlinx/multik/ndarray/operations/IteratingNDArray.kt#L1330)

**Comment by therealansh** [comment]
hey @devcrocod i can try this one. Are we planning to add all the primitive array with all the dimensions like D1, D2 and so on for every primitive array?

**Comment by devcrocod** [comment]
@zaleslaw 
Look here, please. That's what you need?

**Comment by zaleslaw** [comment]
Looks like what I need in KotlinDL
