### ISSUE TITLE
How to create ndArray from Array<FloatArray>

### ISSUE THREAD

**Issue by Techseeker-404** [Kotlin/multik#88]
Have an  Array of float Arrays created using the ```jlibrosa.generateMelspectroGram ``` method from the library https://github.com/Subtitle-Synchronizer/jlibrosa.
```
val sampleRate = 22050
val nMELS = 64
 val hopLENGTH = 1028
val nFFT = 2048 
val melspectrogram = jlibrosa.generateMelSpectroGram(
            signalFeatures,
            sampleRate, nFFT,
            nMELS, hopLENGTH
        )
```

As we further need to take logarithm of melspectrogram (Array<FloatArray>), Using Multik will be a great option . But can't figure out how to convert it to an ndArray.
Is there any way to achieve it ?! 

Nb:- At some point this preprocessing steps will be included in an Android App

**Comment by devcrocod** [comment]
There is no method out of the box.
Please try this:
```kotlin
val array: Array<FloatArray> = ...

val list = array.map { it.toList() }

val ndarray = mk.ndarray(list)
```
This method is not the most optimal in terms of memory. 

I will add relevant issues on this topic.
