### ISSUE TITLE
make publishing multiplatform

### ISSUE THREAD

**Issue by devcrocod** [Kotlin/multik#89]

**Comment by erksch** [comment]
Hey there! Any news on this? MP support is merged but publishing still seems to be missing.

**Comment by devcrocod** [comment]
Hi
You are right, multiplatform solutions for `multik-api` and `multik-jvm` are already done. Now I am engaged in multi-platform support for `multik-native`, there are certain difficulties with cinterop, so it took a long time.

After that, it will be necessary to rename all modules and the corresponding artifacts. In this case, it will be possible to publish new artifacts.
